package socketauction;

import javax.swing.JOptionPane;
import java.io.*;
import java.net.Socket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    public BufferedReader in;
    public PrintWriter out;
    private Socket socket;

    int usrid;
    public int get_userid()
    {
        return usrid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uname = new javax.swing.JLabel();
        upassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        uname.setFont(new java.awt.Font("Batang", 0, 14)); // NOI18N
        uname.setText("Username");
        jPanel1.add(uname);
        uname.setBounds(90, 60, 77, 26);

        upassword.setFont(new java.awt.Font("Batang", 0, 14)); // NOI18N
        upassword.setText("Password");
        jPanel1.add(upassword);
        upassword.setBounds(90, 120, 77, 26);

        jLabel3.setFont(new java.awt.Font("Batang", 0, 14)); // NOI18N
        jLabel3.setText("Not Registered?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 180, 101, 26);

        registerButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        registerButton.setText("Register Here");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton);
        registerButton.setBounds(70, 220, 109, 23);

        loginButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loginButton.setText("Login ");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton);
        loginButton.setBounds(280, 220, 67, 23);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(240, 60, 140, 20);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(240, 130, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac_media_screen-bayekDesert_ncsa.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1080, 1080));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Registration re=new Registration();
        re.setVisible(true);
        //out.println("Registration");
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        if(name.getText().trim().length()==0 || password.getText().trim().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Enter both username and password");
        }
        else
        {
            try
            {
                        String fname=name.getText();
                        String fpassword=password.getText();
                        out.println(fname);                   //sending server name and password
                        out.println(fpassword);

                        String flag = in.readLine();         //reading result and userid from database in server

                            if(flag.equals("false"))
                            {
                               JOptionPane.showMessageDialog(null,"Wrong username or password, enter again"); 
                               this.setVisible(false);
                               //name.setText("");
                               //password.setText("");
                            }
                            else
                            {
                              String uid = in.readLine();
                              usrid = Integer.valueOf(uid).intValue();  //string to int conversion
                             // System.out.print(usrid);
                              this.setVisible(false);
                              Home h=new Home(usrid,fname,socket);
                              h.setVisible(true);                        
                            }

            }
            catch(Exception e){}
        }
    }//GEN-LAST:event_loginButtonActionPerformed
    public void connectToServer() throws IOException {  //function for connection

        // Get the server address from a dialog box.
        String serverAddress = JOptionPane.showInputDialog(null,
            "Enter IP Address of the Server:",
            "Welcome to the Auction system",
            JOptionPane.QUESTION_MESSAGE);

        // Make connection and initialize streams
        socket = new Socket(serverAddress, 9898);
         in = new BufferedReader(
                new InputStreamReader(socket.getInputStream()));
         out = new PrintWriter(socket.getOutputStream(), true);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
               try{ login.connectToServer();} catch(Exception e){ }
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel upassword;
    // End of variables declaration//GEN-END:variables

}
