package socketauction;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */

    
    public Registration() {
        initComponents();
    }
    
    private PrintWriter pw;
    public Registration(Socket socket) throws IOException, IOException
    {
        initComponents();
        System.out.println("inside");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldname = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextFieldphone = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldaddhar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaaddress = new javax.swing.JTextArea();
        errmsg = new javax.swing.JLabel();
        errmsg3 = new javax.swing.JLabel();
        errmsg2 = new javax.swing.JLabel();
        errmsg4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("NAME :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(138, 51, 46, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("PASSWORD :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(102, 99, 82, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("CONFIRM PASSWORD :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(35, 137, 149, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("PHONE NUMBER :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(72, 168, 112, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("E-MAIL ID :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(111, 198, 73, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("ADDHAR NUMBER :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(61, 229, 123, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("ADDRESS :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(115, 262, 69, 17);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(173, 342, 83, 25);

        jTextFieldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnameActionPerformed(evt);
            }
        });
        jTextFieldname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnameKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldname);
        jTextFieldname.setBounds(226, 50, 200, 20);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(226, 98, 200, 20);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(226, 136, 200, 20);

        jTextFieldphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldphoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldphoneKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldphone);
        jTextFieldphone.setBounds(226, 167, 200, 20);
        jPanel1.add(jTextFieldemail);
        jTextFieldemail.setBounds(226, 197, 200, 20);

        jTextFieldaddhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldaddharActionPerformed(evt);
            }
        });
        jTextFieldaddhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldaddharKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldaddhar);
        jTextFieldaddhar.setBounds(226, 228, 200, 20);

        jTextAreaaddress.setColumns(20);
        jTextAreaaddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaaddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(226, 262, 166, 38);
        jPanel1.add(errmsg);
        errmsg.setBounds(295, 191, 0, 0);
        jPanel1.add(errmsg3);
        errmsg3.setBounds(294, 222, 0, 0);
        jPanel1.add(errmsg2);
        errmsg2.setBounds(297, 254, 0, 0);
        jPanel1.add(errmsg4);
        errmsg4.setBounds(300, 161, 0, 0);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ac_media_screen-pyramids_ncsa.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -6, 510, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnameActionPerformed

    private void jTextFieldaddharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldaddharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldaddharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               int phonef=0,adhrf=0,emailf=0,conf=0;
       // Pattern pattern=Pattern.compile("\\d{10}");
        Matcher matcher=Pattern.compile("\\d{10}").matcher(jTextFieldphone.getText());
        if(!matcher.matches())
        {
            jTextFieldphone.setText("");
            errmsg.setText("invalid phone no , enter again");
            
        }
        else phonef=1;
       
        matcher=Pattern.compile("\\d{12}").matcher(jTextFieldaddhar.getText());
        if(!matcher.matches())
        {
            jTextFieldaddhar.setText("");
            errmsg2.setText("invalid adhar no , enter again");
            
        }
        else adhrf=1;
        
        matcher=Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-z]{2,6}$",Pattern.CASE_INSENSITIVE).matcher(jTextFieldemail.getText());
        if(!matcher.matches())
        {
            jTextFieldemail.setText("");
            errmsg3.setText("invalid email id  , enter again");
            
        }
        else emailf=1;
        

        
        if(phonef==1 && adhrf==1 && emailf==1)
        {
        
        String name=jTextFieldname.getText();
        String password=jPasswordField1.getText();
        String phone=jTextFieldphone.getText();
        String email=jTextFieldemail.getText();
        String addhar=jTextFieldaddhar.getText();
        String address=jTextAreaaddress.getText();

        
        
        try{
        Connection con=MysqlConnect.ConnectDB();
        String sql="insert into registeredmembers (NAME,PASSWORD,PHONE,EMAIL,ADDHAR,ADDRESS) values(?,?,?,?,?,?);"; 
        PreparedStatement ps=con.prepareStatement(sql);
        ps.setString(1,name);
        ps.setString(2,password);
        ps.setString(3,phone);
        ps.setString(4,email);
        ps.setString(5,addhar);
        ps.setString(6,address);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this,"Registered Successfully!!");
        
        this.setVisible(false);
        new Login().setVisible(true);
        
        }
        
        catch(Exception e)
        {
          e.printStackTrace();
        }
        
        }
        else
        {
            errmsg.setText("");
            errmsg2.setText("");
            errmsg3.setText("");
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldphoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldphoneKeyPressed

    private void jTextFieldnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetter(c) ||c == KeyEvent.VK_BACK_SPACE  || c == KeyEvent.VK_DELETE )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnameKeyTyped

    private void jTextFieldphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldphoneKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldphoneKeyTyped

    private void jTextFieldaddharKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldaddharKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldaddharKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errmsg;
    private javax.swing.JLabel errmsg2;
    private javax.swing.JLabel errmsg3;
    private javax.swing.JLabel errmsg4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaaddress;
    private javax.swing.JTextField jTextFieldaddhar;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldphone;
    // End of variables declaration//GEN-END:variables
}
